# 项目相关配置
ruoyi:
  # 名称
  name: ZhenShu-Mall
  # 版本
  version: 3.8.3
  # 版权年份
  copyrightYear: 2022
  # 实例演示开关
  demoEnabled: true
  # 文件路径 示例（ Windows配置D:/ruoyi/uploadPath，Linux配置 /home/ruoyi/uploadPath）
  profile: ./
  # 获取ip地址开关
  addressEnabled: false
  # 验证码类型 math 数组计算 char 字符验证
  captchaType: math

# 开发环境配置
server:
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # 连接数满后的排队数，默认为100
    accept-count: 1000
    threads:
      # tomcat最大线程数，默认为200
      max: 800
      # Tomcat启动初始化的线程数，默认值10
      min-spare: 100

# 日志配置
logging:
  level:
    com.zhenshu: debug
    org.springframework: warn

# 用户配置
user:
  password:
    # 密码最大错误次数
    maxRetryCount: 5
    # 密码锁定时间（默认10分钟）
    lockTime: 10

# Spring配置
spring:
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 10MB
      # 设置总上传的文件大小
      max-request-size: 20MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  # redis 配置
  redis:
    # 连接超时时间
    timeout: 10s
    jedis:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 20
        # 连接池中的最大空闲连接
        max-idle: 250
        # 连接池的最大数据库连接数
        max-active: 250
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 2000ms
    client-type: jedis
    wx:
      #单位毫秒
      timeout: 10000
      max-wait: 2000
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    druid:
      # 初始连接数
      initialSize: 30
      # 最小连接池数量
      minIdle: 30
      # 最大连接池数量
      maxActive: 250
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 配置一个连接在池中最大生存的时间，单位是毫秒
      maxEvictableIdleTimeMillis: 900000
      # 配置检测连接是否有效
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      filter:
        stat:
          enabled: true
          # 慢SQL记录
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true
      # 配置监控页功能
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: admin
        resetEnable: false

# MyBatis Plus配置
mybatis-plus:
  # 搜索指定包别名
  typeAliasesPackage: com.zhenshu.**.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations:
    - classpath*:mapper/**/*Mapper.xml
    - classpath*:mapper/**/*Dao.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml
  # 枚举类转换
  typeEnumsPackage: com.zhenshu.**.enums.**

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
  params: count=countSql

# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*

# 接口文档增强模式配置，文档地址：https://doc.xiaominfo.com/knife4j/documentation/enhance.html
knife4j:
  # 是否开启 Knife4j 增强模式
  enable: true
  # 安全校验
  basic:
    # 账号
    username: admin
    # 密码
    password: admin
  # 配置
  setting:
    # 是否显示界面中 SwaggerModel 功能
    enableSwaggerModels: false
    # 是否在每个 Debug 调试栏后显示刷新变量按钮，默认不显示
    enableReloadCacheParameter: false
    # 是否开启界面中对某接口的版本控制，如果开启，后端变化后 Ui 界面会存在小蓝点
    enableVersion: false
